### ISSUE TITLE
Agent Mulder not found in extension manager for ReSharper 9.2

### ISSUE THREAD

**Issue by tsavela** [hmemcpy/AgentMulder#80]
Hi,

I looked at the release notes (https://raw.githubusercontent.com/hmemcpy/AgentMulder/master/WhatsNew.txt) and according to that you are supporting ReSharper 9.2 now?

The problem is that it does not seem to exist in the resharper plugins repository: https://resharper-plugins.jetbrains.com/packages/AgentMulder/ (Latest version 1.2.0 and requires ReSharper 8.1-8.3)

How come the v1.2.9.2 mentioned in the release notes is not available there?

**Comment by dannmichelson** [comment]
I'm finding the same thing. I have Resharper 9.2 (and VS 2015), can't find Agent Mulder in the Extensions list.

**Comment by hmemcpy** [comment]
Huge apologies. Due to a critical bug people had discovered (which I was unable to fix myself), I had to pull the 9.2 version out of the gallery!
Thanks to @SirDuke (of the ReSharper team), it is now fixed, and I will upload a new version shortly!

Apologies for the delay!

**Comment by rikoe** [comment]
Hi - what is the current status of the plugin for Resharper 9.2? I still can't find it in extension manager.

Is there another way of installing it outside of extension manager?

**Comment by AsValeO** [comment]
Hi! **rikoe**, you're not alone. I guess many people are waiting for a new release. Btw looks like R#10 coming soon (EAP5 now released).

**Comment by hmemcpy** [comment]
Very sorry for the delays, everyone!
I just released an updated version (1.3.92) to the gallery. Hopefully it fixes all the issues :(
